### ISSUE TITLE
Synchronizining from new to old

### ISSUE THREAD

**Issue by SanderVO** [RFreij/laravel-synchronize#2]
Hello,

Great package you got here @RFreij !

I've got an issue with your package though. I have multiple synchronizations, and when I run the synchronize command it loops through the files from newest to oldest instead of oldest to newest like the migration command. I'm running into an error right now because a newer synchronization relies on an older one. Can you fix this or make a config variable to set the order?

Thank you!

**Comment by RFreij** [comment]
@SanderVO thank you very much for this issue. 
Sorting from old to new was the expected behaviour so this was a bug.

Released the fix on https://github.com/RFreij/laravel-synchronize/releases/tag/v1.0.4
